# Paramter for simulated annealing
STEP_SIZE = .1
MAX_ITER = 2000
MAX_TEMP = 1000
TEMP_COEFF = 0.99
EPS = 1e-3

# Adaptive simulated annealing
NUM_CYCLES_STEP = 10
NUM_CYCLES_TEMP = 100
NUM_CYCLES_EPS = 4
EPS_THRESH = 0.01
MAX_STEP_SIZE = 0.1

# Parameter for utils
SAFE_MARGIN_COLLISION = 0.01
MARGIN_COLLISION = 1e-6
WEIGHT_SINGLE_STABILITY = 10.0
WEIGHT_COLLISION = 1.0
WEIGHT_TOTAL_STABILITY = 1.0
SINGLE_STABILITY_MARGIN = 0.0

# Parameter for genetic programming
MUTATION_PROBABILITY = 0.5
CROSSOVER_CHILDREN = 10
MAX_POPULATION = 50
MAX_GENERATION = 20
AREA_RATIO_MARGIN = 0.78
SINGLE_AREA_RATIO_MARGIN = 0.1
FITNESS_THRESH = 0.5

TOURNAMENT_K = 10